### PR TITLE
Upgrade lxd client library: 20191225 -> 20230415

### LINKED ISSUE #278: Upgrade LXD API dependency
This version https://github.com/terraform-lxd/terraform-provider-lxd/blob/d6bb607fd8083d5e4654141e930f659a9feffc30/go.mod#L15 lacks things like **config/limits.intances** and **config/features.networks** which is essential in case we want **project** configuration parameters to make sense in the **lxd_network**

### PR DESCRIPTION
**Pull request by adamcstephens**
Two minor updates, including adding a user-agent when getting the remote certificate.

Fixes #278

### CODE REVIEW

**Comment by dorkamotorka** [comment]
This would be pretty cool to upgrade, because the API is quite stall - already affecting our projects

**Comment by adamcstephens** [comment]
I tracked down one of the failures, but the tests are still running into data races. I will need to take a look at the provider tests again that I removed in #289 as I'm concerned that something isn't right in the provider path.

**Comment by gboutry** [comment]
Hi @adamcstephens, is there any additional steps needed for this PR ? I ran the tests locally and on my [fork](https://github.com/gboutry/terraform-provider-lxd/pull/1), and they seem ok.

Do you need help in any way ?

**Comment by adamcstephens** [comment]
@gboutry I've been unable to reproduce the data race in the test failure locally. Unfortunately, it reliably fails through GitHub Actions meaning that something isn't quite right. 

I'd happily take some assistance fixing the race with the tests if you have any insight, or even if you can reproduce them locally.

**Comment by gboutry** [comment]
I tried re-running them on the CI, and they are green for me: https://github.com/gboutry/terraform-provider-lxd/actions

**Comment by gboutry** [comment]
@adamcstephens I've been able reproduce the bug locally in around 1 every 10 runs (quite reliably 10% of the time). I've come up with a patch with which I can't reproduce it at all (tried 80 runs).

Run with env:
```
export TF_ACC="1"
export GO111MODULE="on"
export LXD_REMOTE=local
export LXD_ADDR=localhost
export LXD_PORT=8443
export LXD_GENERATE_CLIENT_CERTS="true"
export LXD_ACCEPT_SERVER_CERTIFICATE="true"
export LXD_SCHEME=https
export LXD_PASSWORD=the-password
```
Run tests
```
for ((i=1;i<=10;i++))  
do
echo "$i" && go test -count=1 -race -run TestAccSnapshot_multiple -timeout 3m -v ./lxd
done
```

Tests ran on my fork: https://github.com/gboutry/terraform-provider-lxd/actions
PR on your branch with the patch: https://github.com/adamcstephens/terraform-provider-lxd/pull/4

**Comment by adamcstephens** [comment]
Thank you @gboutry!!

**Pull request merged**
