### PR TITLE
Drop deprecated lxd_container and lxd_container_file resources

### PR DESCRIPTION
**Pull request by simondeziel**
Depends on https://github.com/terraform-lxd/terraform-provider-lxd/pull/348

The `lxd_publish_image` and `lxd_snapshot` resources still use the legacy names `container` and `container_name` but I left them for another PR.

### CODE REVIEW

**Review by MusicDin — APPROVED** [review]
Very nice :)

**Review by adamcstephens — APPROVED** [review]
Thanks! :pizza:

**Comment by adamcstephens** [comment]
> The `lxd_publish_image` and `lxd_snapshot` resources still use the legacy names `container` and `container_name` but I left them for another PR.

Do you plan to create another PR addressing these?

**Comment by simondeziel** [comment]
> > The `lxd_publish_image` and `lxd_snapshot` resources still use the legacy names `container` and `container_name` but I left them for another PR.
> 
> Do you plan to create another PR addressing these?

Not in the short term so I wouldn't delay the `2.0` provider release for that.

**Comment by adamcstephens** [comment]
@simondeziel can you rebase this?

**Comment by adamcstephens** [comment]
Added https://github.com/terraform-lxd/terraform-provider-lxd/issues/380 to track the needed deprecations so we don't forget about them. I agree we can handle this post-2.0, and would need to anyway since we still have to have a deprecation cycle.

**Review by adamcstephens — APPROVED** [review]
:pizza:

**Pull request merged**
